project:
  type: website
  output-dir: docs

website:
  title: "Stáž ochrany přírody"
  site-url: https://jonasgaigr.github.io/stazochranyprirody/
  repo-url: https://github.com/jonasgaigr/stazochranyprirody

  navbar:
    logo: images/logo-aopk.svg
    left:
      - href: index.qmd
        text: Úvod
      - href: o_stazi.qmd
        text: O stáži
      - href: zdroje.qmd
        text: Zdroje
    right:
      - href: https://aopk.gov.cz/
        text: AOPK ČR

format:
  html:
    theme: cosmo
    toc: true
    title-block-banner: true
    title-block-logo: docs/images/logo-aopk.svg

extra-files:
  - styles.css
